defmodule ElixirStaple.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:votes) do
      # Attribute removal has been commented out to avoid data loss. See the migration generator documentation for more
      # If you uncomment this, be sure to also uncomment the corresponding attribute *addition* in the `down` migration
      # remove :email

      add :answers, {:array, :bigint}, default: []
      add :user_id, references(:users, column: :id, name: "votes_user_id_fkey", type: :uuid)
    end

    alter table(:polls) do
      modify :choices, {:array, :text}, null: false, default: []
      add :invites, {:array, :uuid}, null: false, default: []
    end
  end

  def down do
    alter table(:polls) do
      remove :invites
      modify :choices, {:array, :text}, null: true, default: nil
    end

    drop constraint(:votes, "votes_user_id_fkey")

    alter table(:votes) do
      remove :user_id
      remove :answers
      # This is the `down` migration of the statement:
      #
      #     remove :email
      #

      # add :email, :text, null: false
    end
  end
end